### ISSUE TITLE
"Windows Defender Firewall" want to block communication of testhost.exe

### ISSUE THREAD

**Issue by ThomasTosik** [asimmon/ephemeral-mongo#22]
Hi,

i am testing the migration from Mongo2Go to EphemeralMongo. I am getting a "Windows Defender Firewall" block when using it. This does not seem to happen when using Mongo2Go. Also when i decide to ignore this message or cancel it; it does not have any negative effect on the testrun.
![grafik](https://user-images.githubusercontent.com/4538358/221554787-593feea4-3c7b-4ba2-a07d-a0cc9e531a61.png)

Any idea were this could come from?

Regards

Thomas

**Comment by asimmon** [comment]
Hi @ThomasTosik ,

`testhost.exe` is a [Microsoft process that is copied to the build output](https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022) and used during `dotnet test [...]`.

I might be wrong, but I don't believe this is related to EphemeralMongo or Mongo2Go. This already happened to me when I cloned and compiled projects outside of directories that are already trusted by my Windows Defender settings. And it was not related to these libraries.

I can still explain the main difference between EphemeralMongo or Mongo2Go when it comes to processes:
* Mongo2Go uses .NET Process class to start `mongod.exe` from the `%userprofile%\.nuget\packages` package cache
* EphemeralMongo also uses .NET Process class to start `mongod.exe` from your project output directory.

**Comment by asimmon** [comment]
Hmm actually I understood why Windows Defender Firewall gave you a warning.

That's because EphemeralMongo creates a new `mongod.exe` process which opens an random available port. The firewall kicks in when `mongod.exe` starts. Basically you have to allow `mongod.exe` (which is a child process of `testhost.exe`) to use a port on your machine.

It targets the `testhost.exe` process because when you start your tests, there's a hierarchy of processes that looks like this:

* Parent process: `testhost.exe` (started by your IDE)
  * Child process 1: `dotnet.exe`
    * Child process 2: `mongod.exe`
