### ISSUE TITLE
"Text file busy" on relaunch

### ISSUE THREAD

**Issue by henaff** [asimmon/ephemeral-mongo#33]
The first time i launch my tests, the package works perfectly.
But then if i relaunch my tests i get:

```bash
/usr/lib/dotnet/sdk/6.0.116/Microsoft.Common.CurrentVersion.targets(4812,5): error MSB3027: Could not copy "/home/user/.nuget/packages/ephemeralmongo6.runtime.linux-x64/1.0.0/runtimes/linux-x64/native/mongodb/bin/mongod" to "bin/Debug/net6.0/runtimes/linux-x64/native/mongodb/bin/mongod". Exceeded retry count of 10. Failed.  [/home/user/Desktop/Sources/Project/source/back/Project/Project.PublicBo.Api.Tests/Project.PublicBo.Api.Tests.csproj]
/usr/lib/dotnet/sdk/6.0.116/Microsoft.Common.CurrentVersion.targets(4812,5): error MSB3021: Unable to copy file "/home/user/.nuget/packages/ephemeralmongo6.runtime.linux-x64/1.0.0/runtimes/linux-x64/native/mongodb/bin/mongod" to "bin/Debug/net6.0/runtimes/linux-x64/native/mongodb/bin/mongod". Text file busy : '/home/user/Desktop/Sources/Project/source/back/Project/Project.PublicBo.Api.Tests/bin/Debug/net6.0/runtimes/linux-x64/native/mongodb/bin/mongod' [/home/user/Desktop/Sources/Project/source/back/Project/Project.PublicBo.Api.Tests/Project.PublicBo.Api.Tests.csproj]
```

**Comment by henaff** [comment]
A workaround is to run dotnet clean each time before running tests

**Comment by asimmon** [comment]
Hi @henaff , the MongoDB executables are copied at build time and a few minutes ago I've changed the `CopyToOutputDirectory` value from `Always` to `PreserveNewest`, so that might help to prevent copying files for nothing (see [1.1.2](https://github.com/asimmon/ephemeral-mongo/releases/tag/1.1.2)).

However, it your `mongod` process in your `bin/` directory is still being used, it means that the process was not correctly disposed. You must dispose the `IMongoRunner` that you get when calling `MongoRunner.Run`, and try to reuse it as much as you can in your test project.
