### ISSUE TITLE
Temp data files are filling up the server.

### ISSUE THREAD

**Issue by jamesburton** [asimmon/ephemeral-mongo#34]
We have configured to use EphemeralMongo within our unit tests and now are seeing an accumulation of associated temp database files.  I don't see an option to clean these up after the instance is terminated, so have I missed an option or are there any examples of automating this?  Otherwise this would appear to be a problem as our server has been experiencing disk space issues and swapping to EphemeralMongo appears to have vastly increased them.

**Comment by asimmon** [comment]
Hi @jamesburton, are you disposing the `IMongoRunner` instance you get back from `MongoRunner.Run`?

Because although the data directory is randomly generated by default, it is supposed [to be deleted on disposal](https://github.com/asimmon/ephemeral-mongo/blob/1.1.1/src/EphemeralMongo.Core/MongoRunner.cs#L102), unless you specify your own data directory.

**Comment by jamesburton** [comment]
Thanks, I’ll check ... I have more been relying on the terminating process option so that’s quite possibly the issue. Thanks, James From: Anthony SimmonSent: 02 July 2023 06:35To: asimmon/ephemeral-mongoCc: James Burton; MentionSubject: Re: [asimmon/ephemeral-mongo] Temp data files are filling up the server. (Issue #34) Hi @jamesburton, are you disposing the IMongoRunner instance you get back from MongoRunner.Run?Because although the data directory is randomly generated by default, it is supposed to be deleted on disposal, unless you specify your own data directory.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
