### ISSUE TITLE
Problem using Aggregate -> Limit on EphemeralMongo5 1.1.2

### ISSUE THREAD

**Issue by BrightProgramming** [asimmon/ephemeral-mongo#41]
I have some code that does a Limit as part of an Aggregate.
On 1.1.2 - I get 

```
System.MissingMethodException
Method not found: 'MongoDB.Driver.IAggregateFluent`1<!0> MongoDB.Driver.IAggregateFluent`1.Limit(Int32)'.
```

0.1.3 -> Works
1.0.0 -> Works
1.1.0 -> Fails
1.1.2 -> Fails

Sample source code:

```
  var customerEvents = await mongoDbContext.CustomerCollection.Aggregate()
      .Match(filterLastThreeMonths)
      .Sort(sortByCreated)
      .Limit(500)
      .ToListAsync();
```
I know there other ways I could have written this code, but this is a simplification from what I'm actually using.

It used to work on Mongo2Go, but I'm trying to migrate away from it.

**Comment by asimmon** [comment]
It seems related to the MongoDB C# driver. Currently EphemeralMongo as a dependency on [MongoDB.Driver](https://www.nuget.org/packages/MongoDB.Driver/) >= 2.19.0.

Since, there has been 3 new versions: [2.19.1](https://www.nuget.org/packages/MongoDB.Driver/2.19.1), [2.19.2](https://www.nuget.org/packages/MongoDB.Driver/2.19.2) and [2.20.0](https://www.nuget.org/packages/MongoDB.Driver/2.20.0).

Could you try to install these instead and see if it fixes you issue? I might also bump the MongoDB.Driver to a newer version later on.

**Comment by ivorb-ps** [comment]
No joy I'm afraid. Using EphemeralMongo 1.1.2 and MongoDB.Driver 2.20.0 - I still get the exception...

`System.MissingMethodException : Method not found: 'MongoDB.Driver.IAggregateFluent`1<!0> MongoDB.Driver.IAggregateFluent`1.Limit(Int32)'.`

**Comment by asimmon** [comment]
I have upgraded the MongoDB C# driver dependency to version 2.20.0. The timing was good as it also helped support MongoDB 7.
